import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nippoBold = localFont({
  src: "../fonts/Nippo-Bold.woff2",
  variable: "--font-nippo-bold",
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} 
          ${geistMono.variable} 
          ${nippoBold.variable} 
          antialiased`}
      >
        <link rel="icon" href="assets/icon.png" type="image/png" sizes="32x32" />
        {children}
      </body>
    </html>
  );
}
